thecut/events/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import feeds, views
from django.conf.urls import include, url


urls = [

    url(r'^$',
        views.ListView.as_view(), name='event_list'),
    url(r'^(?P<page>\d+)$',
        views.ListView.as_view(), name='event_list'),
    url(r'^(?P<slug>[\w-]+)/$',
        views.ListView.as_view(), name='event_list'),
    url(r'^(?P<slug>[\w-]+)/(?P<page>\d+)$',
        views.ListView.as_view(), name='event_list'),

    url(r'^latest\.xml$',
        feeds.LatestEventFeed(), name='event_feed'),
    url(r'^(?P<slug>[\w-]+)/latest\.xml$',
        feeds.LatestCategoryEventFeed(), name='event_feed'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[\w-]+)$',
        views.DetailView.as_view(), name='event_detail'),

    # These old url names are kept for backwards-compatibility
    url(r'^(?P<page>\d+)$',
        views.ListView.as_view(), name='paginated_event_list'),
    url(r'^(?P<slug>[\w-]+)/$',
        views.ListView.as_view(), name='category_event_list'),
    url(r'^(?P<slug>[\w-]+)/(?P<page>\d+)$',
        views.ListView.as_view(), name='paginated_category_event_list'),
    url(r'^(?P<slug>[\w-]+)/latest\.xml$',
        feeds.LatestCategoryEventFeed(), name='category_event_feed'),

]

urlpatterns = [
    url(r'^', include(urls, namespace='events')),
]

thecut/events/templates/events/base.html
{% extends "base.html" %}

thecut/events/templates/events/event_detail.html
{% extends "events/base.html" %}


{% block title %}{{ event.title }} - {{ block.super }}{% endblock %}


{% block extrahead %}
  {{ block.super }}
  {% if event and not event.is_indexable %}<meta name="robots" content="noindex" />{% endif %}
  {% if event.meta_description %}<meta name="description" content="{{ event.meta_description }}" />{% endif %}
{% endblock %}


{% block content %}

  <h1>{{ event.heading }}</h1>
  {% if not event.end_at %}
    <h2>{{ event.start_at|date:"DATETIME_FORMAT" }}</h2>
  {% else %}
    {% ifequal event.start_at.date event.end_at.date %}
      {% ifequal event.start_at.time event.end_at.time %}
        <h2>{{ event.start_at|date:"DATETIME_FORMAT" }}</h2>
      {% else %}
        <h2>{{ event.start_at|date:"DATETIME_FORMAT" }} to {{ event.end_at|date:"TIME_FORMAT" }}</h2>
      {% endifequal %}
    {% else %}
      <h2>{{ event.start_at|date:"DATETIME_FORMAT" }} to {{ event.end_at|date:"DATETIME_FORMAT" }}</h2>
    {% endifequal %}
  {% endif %}

  {% if event.featured_content %}<div>{{ event.featured_content }}</div>{% endif %}
  {% if event.content %}<div>{{ event.content|safe }}</div>{% endif %}

{% endblock %}

thecut/events/templates/events/event_list.html
{% extends "events/base.html" %}


{% block title %}{{ category|default:"Events" }} - {{ block.super }}{% endblock %}


{% block extrahead %}
  {{ block.super }}

  {% if category %}
    {% if category and not category.is_indexable %}<meta name="robots" content="noindex" />{% endif %}
    {% if category.meta_description %}<meta name="description" content="{{ category.meta_description }}" />{% endif %}
    <link rel="alternate" href="{% url "events:event_feed" slug=category.slug %}" type="application/atom+xml" title="Latest {{ category }}" />
  {% else %}
    <link rel="alternate" href="{% url "events:event_feed" %}" type="application/atom+xml" title="Latest events" />
  {% endif %}

  {% if page_obj.paginator.num_pages > 1 %}{% spaceless %}
    {% if page_obj.has_previous %}
      {% if category %}
        <link rel="prev" href="{% if page_obj.previous_page_number == 1 %}{% url "events:event_list" slug=category.slug %}{% else %}{% url "events:event_list" slug=category.slug page=page_obj.previous_page_number %}{% endif %}" />
      {% else %}
        <link rel="prev" href="{% if page_obj.previous_page_number == 1 %}{% url "events:event_list" %}{% else %}{% url "events:event_list" page=page_obj.previous_page_number %}{% endif %}" />
      {% endif %}
    {% endif %}
    {% if page_obj.has_next %}
      {% if category %}
        <link rel="next" href="{% url "events:event_list" slug=category.slug page=page_obj.next_page_number %}" />
      {% else %}
        <link rel="next" href="{% url "events:event_list" page=page_obj.next_page_number %}" />
      {% endif %}
    {% endif %}
  {% endspaceless %}{% endif %}
{% endblock %}


{% block content %}

  <h1>{{ category|default:"Events" }}</h1>
  {% if category.featured_content %}<div>{{ category.featured_content }}</div>{% endif %}
  {% if category.content %}<div>{{ category.content|safe }}</div>{% endif %}

  {% for event in event_list %}
  {% if forloop.first %}<ul>{% endif %}
    <li>
      <a href="{{ event.get_absolute_url }}">
        {{ event.start_at|date:"DATETIME_FORMAT" }}
        {{ event }}
      </a>
    </li>
  {% if forloop.last %}</ul>{% endif %}
  {% empty %}
    <p>No events to display.</p>
  {% endfor %}

  {% if page_obj.paginator.num_pages > 1 %}
  <div>
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

    {% if page_obj.has_previous %}
      {% if category %}
        <a href="{% if page_obj.previous_page_number == 1 %}{% url "events:event_list" slug=category.slug %}{% else %}{% url "events:event_list" slug=category.slug page=page_obj.previous_page_number %}{% endif %}" rel="previous">previous</a>
      {% else %}
        <a href="{% if page_obj.previous_page_number == 1 %}{% url "events:event_list" %}{% else %}{% url "events:event_list" page=page_obj.previous_page_number %}{% endif %}" rel="previous">previous</a>
      {% endif %}
    {% endif %}

    {% if page_obj.has_next %}
      {% if category %}
        <a href="{% url "events:event_list" slug=category.slug page=page_obj.next_page_number %}" rel="next">next</a>
      {% else %}
        <a href="{% url "events:event_list" page=page_obj.next_page_number %}" rel="next">next</a>
      {% endif %}
    {% endif %}

  </div>
  {% endif %}

{% endblock %}